spring:
  application:
    name: devhelper-backend

  profiles:
    default: local

  jackson:
    default-property-inclusion: non_null
    serialization:
      indent_output: true


# Default storage path (overridden per profile)
file:
  storage:
    base-path: ./data

app:
  logging:
    path: ${LOG_PATH:./logs}
    level:
      com:
        devhelper: INFO
      org:
        springframework:
          web: INFO


server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always


logging:
  level:
    com.devhelper: INFO
    org.springframework.web: INFO
