spring:
  application:
    name: devhelper-backend

  jackson:
    default-property-inclusion: non_null
    serialization:
      indent_output: true


server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always


logging:
  level:
    com.devhelper: DEBUG
    org.springframework.web: INFO
